### ISSUE TITLE
aspnetcore-load-balancing-master_nginx => error

### ISSUE THREAD

**Issue by jamalkaksouri** [giansalex/aspnetcore-load-balancing#1]
Hi, I using command for running this app

git clone https://github.com/giansalex/aspnetcore-load-balancing.git
    cd aspnetcore-load-balancing
    docker-compose build
    docker-compose up -d --scale core-app=4 --no-recreate

But in the last command, I received the following error : 
 
![Image of Yaktocat](https://cdn1.imggmi.com/uploads/2019/3/4/347efd49f658b10e6edef6d8f5c43b88-full.png)

In docker image files two file created:

![Image of Yaktocat](https://cdn1.imggmi.com/uploads/2019/3/4/fba0606af6481fec9bd23ac51ba4b91b-full.png)

When I run the first imagefile on custom port, it works without problems:

![Image of Yaktocat](https://cdn1.imggmi.com/uploads/2019/3/4/04ccec12b91a0a93d1200037e44e9d5a-full.png)

But second imagefile not working and get an error : 

![Image of Yaktocat](https://cdn1.imggmi.com/uploads/2019/3/4/007f3f14f03c9dc19e5bda92322e2cba-full.png)

**Comment by giansalex** [comment]
Hello @jamalkaksouri, can you remove the container `5a3a05a3b...`, and run last command again

**Comment by jamalkaksouri** [comment]
I remove the container `5a3a05a3b...` and run last command again, But received last error again!

**Comment by giansalex** [comment]
Should run `docker-compose up -d --scale core-app=4 --no-recreate`, not create containers manually.

**Comment by jamalkaksouri** [comment]
I try to run it, But it's not working

```
C:\Users\Developer\Desktop\aspnetcore-load-balancing-master\aspnetcore-load-balancing-master>docker-compose up -d --scale core-app=4 --no-recreate
Starting aspnetcore-load-balancing-master_core-app_1 ... done
Starting aspnetcore-load-balancing-master_core-app_2 ... done
Starting aspnetcore-load-balancing-master_core-app_3 ... done
Starting aspnetcore-load-balancing-master_core-app_4 ... done
Creating core-app.local                              ... error

ERROR: for core-app.local  Cannot start service nginx: driver failed programming external connectivity on endpoint core-app.local (346af68079e4d459a55c74d915d626c6b9124ff45ac23481af51ca4e6c14633a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint core-app.local (346af68079e4d459a55c74d915d626c6b9124ff45ac23481af51ca4e6c14633a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied
ERROR: Encountered errors while bringing up the project.
```

**Comment by giansalex** [comment]
Run `docker container ls`, and stop containers on port 80, or other services in your computer on port 80

**Comment by jamalkaksouri** [comment]
I try this command for stop all container, `docker stop $(docker ps -aq)`. But unfortunately, the current command failed again.

**Comment by giansalex** [comment]
Not rename directory àfter git clone: `aspnetcore-load-balancing` or edit `/nginx/nginx.conf` with your containers created.

**Comment by jamalkaksouri** [comment]
I using following command ; 

```
git clone https://github.com/giansalex/aspnetcore-load-balancing.git
    cd aspnetcore-load-balancing
    docker-compose build
    docker-compose up -d --scale core-app=4 --no-recreate
```

I not change or edit path or folder name's and try to this command `docker-compose rm -s -v`, But it's not working and get the error

**Comment by giansalex** [comment]
On first image, i see `aspnetcore-load-balancing-master` as directory.
> Directory name should be `aspnetcore-load-balancing`

**Comment by jamalkaksouri** [comment]
I've already changed this path and tried it but not working

**Comment by giansalex** [comment]
Can you try in [play-docker](https://labs.play-with-docker.com)
![image](https://user-images.githubusercontent.com/14926587/53754350-b7fc9d80-3e81-11e9-8653-50e859ca908c.png)

https://ip172-18-0-20-bhums34pkul000as5ic0-443.direct.labs.play-with-docker.com/

**Comment by jamalkaksouri** [comment]
But why is not working on my localhost PC?
In docker application i switching in Linux containers.

**Comment by giansalex** [comment]
I have windows computer, and it works.
Maybe another process use port 80.
